package com.distributed_lovable.intelligence_service.dto.chat;


import com.distributed_lovable.common_lib.enums.MessageRole;

import java.time.Instant;
import java.util.List;

public record ChatResponse(
        Long id,
        String content,
        MessageRole role, // Message role present in enum ex assistant means generated by llm , user means asked by me
        List<ChatEventResponse> events,
        Integer tokensUsed,
        Instant createdAt

)
{ }
