package com.distributed_lovable.intelligence_service.entity;

import com.distributed_lovable.common_lib.enums.MessageRole;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.List;

@FieldDefaults(level = AccessLevel.PRIVATE)
@Getter
@Setter
@Entity
@Table(name = "chat_messages")
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChatMessages {

    //  when user ask something and llm replies that whole will be one chatmessage and in the same session of user ask anything else
    // and llm replies again then that will be different chatMessage in same chat sessionn
    // and multiple things inside one chatmessage are events ex- thinking genreating files etc.. see in chateventenum
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;

    @ManyToOne(fetch = FetchType.LAZY,optional = false)
    @JoinColumns({
            @JoinColumn(name = "project_id",referencedColumnName = "projectId",nullable = false),
            @JoinColumn(name = "user_id",referencedColumnName = "userId",nullable = false)
    })
    ChatSession chatSession;

    @Column(columnDefinition = "text")
    String content; // null unless USER role not for Assistant that will be empty

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    MessageRole role; // Message role present in enum ex assistant means generated by llm , user means asked by me

    @OneToMany(mappedBy = "chatMessage" , cascade = CascadeType.ALL ,fetch = FetchType.LAZY)
    @OrderBy("sequenceOrder ASC") // now everything will be marked in sequence of ChatEvent's field sequence by
    List<ChatEvent> events; // empty unless Assistant role

    //String toolCalls;

    Integer tokensUsed=0;

    @CreationTimestamp
    Instant createdAt;
}
